version: 1.0.{build}
image: Visual Studio 2022

branches:
  only:
  - master

before_build:
  - nuget restore

build:
  project: ImplementProject.sln
  verbosity: minimal

after_build:
  # Generate the .exe file for the .NET 8 application
  - dotnet publish -c Release -r win-x64 --self-contained true -o .\publish

artifacts:
  - path: publish\**\*.exe
    name: MyAppExecutable
    type: exe
