version: 1.0.{build}
image: Visual Studio 2022

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

build:
  project: ImplementProject.sln

test_script:
  - dotnet test ImplementProject.Tests/ImplementProject.Tests.csproj

artifacts:
  - path: 'ImplementProject/bin/Release/**/*'
    name: 'PublishedApp'
    type: zip
